# Generated by Django 2.1.7 on 2019-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailCheckMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=255)),
                ('msg_subject', models.CharField(blank=True, max_length=255)),
                ('msg_from', models.EmailField(max_length=200)),
                ('msg_to', models.EmailField(max_length=200)),
                ('msg_date', models.DateTimeField()),
                ('msg_body', models.TextField(blank=True, help_text='Can contain both text and html versions of messages (multi-part)')),
            ],
        ),
    ]
